enable_cache: False

settings:
  docker:
    required_integrations:
      - mlflow

# Configuration of the Model Control Plane
model:
  name: prices_car_predictor
  license: Apache 2.0
  description: Predictor of used car prices.
  tags: ["regression", "car", "price_prediction"]
